name: prs1
channels:
  - conda-forge
dependencies:
  - conda-forge::numpy=1.18.1
  - conda-forge::pandas=1.0.1
  - conda-forge::pip=19.3.1
  - conda-forge::python=3.8.1
  - conda-forge::scikit-learn=0.22.1
  - conda-forge::scikit-allel=1.2.1
  - conda-forge::scipy=1.4.1
  - conda-forge::statsmodels=0.10.1
  - conda-forge::tqdm=4.31.1
  - conda-forge::r-tidyverse=1.3.0
  - conda-forge::r-irkernel=1.1
  - conda-forge::r-ggplot2=3.3.0
  - conda-forge::r-boot=1.3_24
  - conda-forge::r-cowplot=1.0.0
  - conda-forge::r-ggforce=0.3.1
  - conda-forge::r-base=3.6.2
  - conda-forge::r-asbio=1.6_1
  - conda-forge::r-ggrepel=0.8.1
  - conda-forge::r-gridextra=2.3
  - conda-forge::pandas-plink
  - conda-forge::rpy2
  - conda-forge::networkx
  - conda-forge::r-ckmeans.1d.dp 
  - conda-forge::bitarray 
  - pip:
    - joblib
    - pytz
    - python-dateutil
    - pyarrow
